SRC_DIR := ./src
INC_DIR := ./include
BIN_DIR := ./bin
CC := gcc
CFLAGS := -o
$(BIN_DIR)/sever : $(SRC_DIR)/sever.c $(SRC_DIR)/main.c
	$(CC) $(CFLAGS) $@ $(SRC_DIR)/sever.c $(SRC_DIR)/main.c -I $(INC_DIR)
